packages:
  - apps/*
  - packages/*

catalogs:
  build:
    vite: ^8.2.2
  dev:
    knip: ^6.34.0
    pncat: ^0.13.3
    simple-git-hooks: ^2.14.0
    taze: ^21.1.0
    typescript: ^6.0.3
  frontend:
    '@antfu/design': ^0.4.0
    '@antfu/utils': ^9.0.0
    '@iconify-json/ph': ^1.2.2
    '@unocss/preset-icons': ^66.10.0
    '@unocss/reset': ^66.10.0
    '@unocss/transformer-directives': ^66.10.0
    '@vitejs/plugin-vue': ^6.0.8
    colorjs.io: ^0.6.1
    reka-ui: ^2.6.0
    unocss: ^66.10.0
    vue: ^3.5.42
    vue-tsc: ^3.3.11
  lint:
    '@octohash/eslint-config': ^0.6.1
    eslint: ^10.10.0
    lint-staged: ^17.5.0
  prod:
    xlsx: ^0.18.5
  test:
    vitest: ^5.0.0
  types:
    '@types/node': ^24.10.1
